### ISSUE TITLE
fix autoguider bug when not dithering

### ISSUE THREAD

**Issue by lspitler** [AstroHuntsman/huntsman-pocs#59] opened 2018-08-02 22:47 UTC
Note from @AnthonyHorton during August/July 2018 run:

patch has made autoguider situation worse. It's not dithering, but at the start of every image it interrupts the guiding by asking the autoguider to take an image, then hits an error so doesn't restart the guiding. Have to manually restart by hitting the autoguide button, but now it's every 30 seconds instead of 300.

**Comment by wtgee** [comment] 2018-11-26 03:22
FYI, during a run last night we figured out that any reschedule attempt was doing bad things with the guider, which for some reason was happening during the `dithering` state even for non-dithered observations. Created #99, which is probably a duplicate of this.

**Closed** 2020-11-09 03:36 UTC
